import {JSDOM} from 'jsdom';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
const root=new URL('../',import.meta.url),temp=await mkdtemp(join(tmpdir(),'everyday-ui-'));
const dom=new JSDOM(await readFile(new URL('index.html',root),'utf8'),{url:'http://localhost/fitness-tracker/'});
const initialHome=['.home-actions','.today-card','.weight-strip'].map(selector=>{
 const element=dom.window.document.querySelector(selector);assert.ok(element,'present before JavaScript: '+selector);return element.outerHTML;
});
assert.ok(dom.window.document.querySelector('.home-actions button').disabled);
assert.ok(!dom.window.document.body.textContent.includes('Goals are guides, not grades'));
for(const key of ['window','document','localStorage','navigator'])Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true});
let storagePersisted=false,persistRequests=0;
Object.defineProperty(dom.window.navigator,'storage',{configurable:true,value:{persisted:async()=>storagePersisted,persist:async()=>{persistRequests++;storagePersisted=true;return true;},estimate:async()=>({usage:4096,quota:1024*1024})}});
globalThis.alert=()=>{};globalThis.confirm=()=>true;
const fixture=join(temp,'cloud.mjs');
await writeFile(fixture,`
 import {CloudSession,nextRecord} from '${new URL('cloud-model.js',root)}';
 export const state={user:'alice',records:new Map(),fail:false,callback:null};
 const store={read:async uid=>state.records.get(uid)||null,write:async(uid,revision,payload)=>{if(state.fail)throw Error('offline');const next=nextRecord(state.records.get(uid)||null,revision,payload);state.records.set(uid,next);return next;}};
 export const cloudError=e=>e.message;
 export async function connectCloud(callback){state.callback=callback;await new Promise(resolve=>{state.releaseAuth=resolve;});await callback(null,null);return {signIn:async()=>callback({uid:state.user,email:state.user+'@example.com'},new CloudSession(state.user,store)),signOut:async()=>callback(null,null)};}
`);
let source=await readFile(new URL('app.js',root),'utf8');
source=source.replaceAll("'./data.js?v=51'",`'${new URL('data.js',root)}'`);
source=source.replaceAll("'./cloud-model.js?v=51'",`'${new URL('cloud-model.js',root)}'`);
source=source.replaceAll("'./import-model.js?v=51'",`'${new URL('import-model.js',root)}'`);
source=source.replaceAll("'./durability.js?v=51'",`'${new URL('durability.js',root)}'`);
source=source.replaceAll("'./cloud.js?v=51'",`'${pathToFileURL(fixture)}'`);
await writeFile(join(temp,'app.mjs'),source);
const tick=()=>new Promise(r=>setTimeout(r,20));
const click=async action=>{const el=document.querySelector(`[data-action="${action}"]`);assert.ok(el,action);el.click();await tick();};
const submit=async(kind,values)=>{const form=document.querySelector(`[data-form="${kind}"]`);for(const [name,value]of Object.entries(values))form.elements.namedItem(name).value=value;form.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await tick();};
// Node's FormData doesn't consume HTML forms; use the DOM's implementation.
globalThis.FormData=dom.window.FormData;
try{
 await import(pathToFileURL(join(temp,'app.mjs')));await tick();await tick();
 assert.equal(persistRequests,1,'startup requests persistent origin storage once');
 const {state}=await import(pathToFileURL(fixture));
 assert.ok(document.querySelector('.home-actions'),'Home cards exist before auth finishes');
 assert.equal(document.querySelector('main').getAttribute('aria-busy'),'true');
 for(const [i,selector] of ['.home-actions','.today-card','.weight-strip'].entries())assert.equal(document.querySelector(selector).outerHTML,initialHome[i],'initial HTML matches pending layout');
 assert.equal(document.querySelector('.metric-row b').textContent,'—');
 assert.ok(document.querySelector('.home-actions button').disabled);
 assert.ok(!document.querySelector('main').textContent.includes('Connecting'));
 state.releaseAuth();await tick();await tick();
 assert.equal(document.querySelector('main').getAttribute('aria-busy'),'false');
 assert.ok(document.querySelector('main').firstElementChild.classList.contains('home-actions'));
 assert.ok(document.querySelector('main').nextElementSibling.classList.contains('account-banner'));
 await click('food');assert.ok(document.querySelector('.tracking-date input'));await click('new-food');
 assert.equal(document.activeElement.getAttribute('role'),'dialog','opening forms must not autofocus an input');await submit('food',{name:'Device meal',calories:'250',protein:'20'});
 assert.equal(JSON.parse(localStorage.getItem('everyday-fitness-v1')).foodEntries.length,1);
 await click('sign-in');await click('food');
 assert.ok(!document.querySelector('main').textContent.includes('Device meal'),'no automatic migration');
 await click('settings');await click('migrate-device');
 assert.equal(JSON.parse(state.records.get('alice').payload).foodEntries.length,1);
 await click('sign-out');state.user='bob';await click('sign-in');await click('food');
 assert.ok(!document.querySelector('main').textContent.includes('Device meal'),'account separation');
 state.fail=true;await click('new-food');await submit('food',{name:'Cloud meal',calories:'100',protein:'8'});
 assert.ok(document.querySelector('.save-warning'),'unsaved error is visible');assert.equal(state.records.has('bob'),false);
 assert.ok(localStorage.getItem('everyday-cloud-recovery-v1:bob'),'failed cloud save leaves an account-scoped device recovery copy');
 state.fail=false;await click('cloud-retry');assert.equal(JSON.parse(state.records.get('bob').payload).foodEntries[0].name,'Cloud meal');
 assert.equal(localStorage.getItem('everyday-cloud-recovery-v1:bob'),null,'successful cloud save clears the recovery copy');
 assert.ok(localStorage.getItem('everyday-cloud-confirmed-v1:bob'),'successful cloud save keeps a last-confirmed device copy');
 assert.equal(JSON.parse(localStorage.getItem('everyday-fitness-v1')).foodEntries[0].name,'Device meal','cloud record never replaces local data');
 await click('gym');assert.ok(document.querySelector('.tracking-date input'));
 const dateInput=document.querySelector('.tracking-date input');dateInput.value='2026-09-20';dateInput.dispatchEvent(new dom.window.Event('change',{bubbles:true}));await tick();
 await click('custom-lift');await submit('lift',{exercise:'Test press',weight:'40',reps:'8',difficulty:'7'});
 assert.equal(JSON.parse(state.records.get('bob').payload).lifts[0].date,'2026-09-20');
 await click('home');await click('weight');await submit('weight',{value:'180',date:'2026-09-20'});
 await click('progress');await click('body-fat');await submit('body-fat',{value:'22.4',date:'2026-09-20'});
 await click('progress');assert.ok(document.querySelector('main').textContent.includes('180'));assert.ok(document.querySelector('.weight-progress-chart'),'weigh-in chart renders');assert.ok(document.querySelector('.weight-actual-dot'),'exact weigh-in point renders');assert.ok(document.querySelector('.bodyfat-progress-chart'),'body fat chart renders');assert.equal(JSON.parse(state.records.get('bob').payload).bodyFat[0].value,22.4);
 await click('home');assert.ok(document.querySelector('.travel-notes-panel'),'trip notes are available from Home');
 await click('day-note');await submit('day-note',{date:'2026-09-20',text:'Embarkation day · lots of walking'});
 await click('meal-memory');await submit('meal-memory',{date:'2026-09-20',text:'Dinner menu and plate photographed',noteTime:'36'});
 let noteState=JSON.parse(state.records.get('bob').payload);assert.equal(noteState.notes.length,2);assert.equal(noteState.notes.find(n=>n.type==='meal').t,36);
 await click('food');const noteDate=document.querySelector('.tracking-date input');noteDate.value='2026-09-20';noteDate.dispatchEvent(new dom.window.Event('change',{bubbles:true}));await tick();assert.ok(document.querySelector('.travel-notes-panel').textContent.includes('Dinner menu and plate photographed'));
 await click('settings');
 let exported;const originalCreate=URL.createObjectURL;URL.createObjectURL=blob=>{exported=blob;return 'blob:test';};
 dom.window.HTMLAnchorElement.prototype.click=function(){};
 await click('export');const backup=JSON.parse(await exported.text());URL.createObjectURL=originalCreate;
 assert.equal(backup.lifts.length,1);assert.equal(backup.weights.length,1);assert.equal(backup.notes.length,2);
 await click('import-data');await click('import-csv');let form=document.querySelector('[data-form="import"]');
 Object.defineProperty(form.querySelector('[name="file"]'),'files',{value:[{size:100,text:async()=> 'date,name,calories,protein,quantity\n2026-09-19,CSV meal,300,25,1'}]});
 form.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await tick();await click('commit-import');
 assert.equal(JSON.parse(state.records.get('bob').payload).foodEntries.length,2);
 await click('import-data');await click('restore');form=document.querySelector('[data-form="import"]');
 Object.defineProperty(form.querySelector('[name="file"]'),'files',{value:[{size:100,text:async()=>JSON.stringify(backup)}]});
 form.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await tick();await click('commit-import');
 assert.deepEqual(JSON.parse(state.records.get('bob').payload),backup,'JSON restore preserves the exported snapshot');
 // Pass 2: selected-day preview and full log share the same entries/totals.
 await click('food');
 const setDate=async value=>{const field=document.querySelector('.tracking-date input');field.value=value;field.dispatchEvent(new dom.window.Event('change',{bubbles:true}));await tick();};
 await setDate('2025-01-02');
 assert.ok(document.querySelector('.food-preview-empty'));
 assert.ok(document.querySelector('.food-day').nextElementSibling.textContent.includes('Saved foods'));
 await click('food-log');assert.equal(document.querySelectorAll('.full-food-log .list-row').length,0);await click('close');
 for(let i=1;i<=5;i++){
  await click('new-food');await submit('food',{name:'History food '+i,calories:'100',protein:'10',quantity:'2'});
  assert.equal(document.querySelectorAll('.food-preview-row').length,Math.min(i,3));
  assert.equal(document.querySelector('.food-total-number strong').textContent,String(i*200));
 }
 assert.deepEqual([...document.querySelectorAll('.food-preview-row strong')].map(e=>e.textContent),['History food 5','History food 4','History food 3']);
 await click('food-log');assert.equal(document.querySelectorAll('.full-food-log .list-row').length,5);
 assert.ok(document.querySelector('.modal').textContent.includes('2025-01-02'));
 await click('edit-entry');await submit('food',{name:'Edited historical food',calories:'150',protein:'15',quantity:'2'});
 assert.equal(document.querySelector('.food-total-number strong').textContent,'1100');
 await click('food-log');await click('edit-entry');await click('delete-entry');
 assert.equal(document.querySelector('.food-total-number strong').textContent,'800');
 assert.equal(document.querySelectorAll('.food-preview-row').length,3);
 const countBeforeSaved=JSON.parse(state.records.get('bob').payload).foodEntries.length;
 await click('add-saved');assert.ok(document.querySelector('[data-form="food"]'),'saved card opens normal food form');assert.equal(document.querySelector('[data-form="food"] [name="date"]').value,'2025-01-02');await submit('food',{quantity:'0.5'});
 let current=JSON.parse(state.records.get('bob').payload);assert.equal(current.foodEntries.at(-1).date,'2025-01-02');assert.equal(current.foodEntries.at(-1).quantity,0.5);assert.ok(document.querySelector('.food-undo-toast'));
 await click('undo-food-add');assert.equal(JSON.parse(state.records.get('bob').payload).foodEntries.length,countBeforeSaved,'saved-food undo removes only the new entry');
 await click('today');assert.ok(document.querySelector('.food-main span').textContent.includes('Add to today'));
 assert.ok(!document.querySelector('.food-preview').textContent.includes('History food'));
 await click('add-saved');assert.ok(document.querySelector('[data-form="food"]'));await submit('food',{quantity:'1'});current=JSON.parse(state.records.get('bob').payload);
 assert.equal(current.foodEntries.at(-1).date,document.querySelector('.tracking-date input').value);
 // Pass 3: nested Food dismissal returns exactly one level.
 await click('food-log');await click('edit-entry');
 document.querySelector('.modal .close-btn').click();await tick();
 assert.ok(document.querySelector('.full-food-log'));
 await click('edit-entry');
 document.querySelector('.modal').dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await tick();
 assert.ok(document.querySelector('.full-food-log'));
 await click('new-food');await click('close');assert.ok(document.querySelector('.full-food-log'));
 await click('close');assert.ok(!document.querySelector('.modal'));
 await click('new-food');await click('close');assert.ok(!document.querySelector('.modal'),'direct add dismisses to Food');
 // Calendar keeps Friday as the fixed week boundary and never modifies historical records.
 await click('home');await click('weight');await submit('weight',{value:'178',date:'2026-09-21'});
 await click('settings');
 const recordsBefore=JSON.parse(state.records.get('bob').payload);
 await submit('week-settings',{dayResetMinutes:'360'});
 const savedCalendar=JSON.parse(state.records.get('bob').payload);
 assert.equal(savedCalendar.settings.weekStart,5);
 for(const key of ['weights','lifts','foods','foodEntries'])assert.deepEqual(savedCalendar[key],recordsBefore[key]);
 await click('progress');
 const {weeklyWeights,startOfWeek,localDate}=await import(new URL('data.js',root));
 const visibleWeeks=weeklyWeights(savedCalendar.weights,68,'lb',5).slice(0,6);
 assert.deepEqual([...document.querySelectorAll('[data-week]')].map(e=>e.dataset.week),visibleWeeks.map(w=>w.week));
 assert.ok(document.querySelector('.progress-trend .weight-progress-chart'),'weight graph lives in Weekly trend');
 assert.ok(!document.querySelector('.weight-progress-panel .weight-progress-chart'),'individual weigh-ins is list-only');
 assert.ok(document.querySelector('.week-setting').textContent.includes('Friday'));
 assert.ok(!document.querySelector('.week-setting').textContent.includes('Change'));
 assert.ok(document.querySelectorAll('.weight-progress-panel .list-row').length<=5);
 assert.ok(document.querySelectorAll('.exercise-progress-panel .exercise-progress-link').length<=4);
 const progressExercise=document.querySelector('.exercise-progress-panel .progress-exercise-card');if(progressExercise){assert.ok(progressExercise.classList.contains('exercise'),'progress uses Lifting exercise card shell');assert.ok(progressExercise.querySelector('.equipment-art'),'progress exercise includes equipment art');assert.ok(progressExercise.className.includes('equipment-'),'progress exercise includes equipment color class');}
 assert.ok(document.querySelector('.food-progress-chart'),'nutrition graph renders');
 assert.equal(document.querySelectorAll('.food-period-tabs [data-action="food-progress-period"]').length,4,'week/month/quarter/year controls render');
 const monthTab=document.querySelector('[data-action="food-progress-period"][data-period="month"]');monthTab.click();await tick();assert.equal(document.querySelector('.food-period-tabs .active')?.dataset.period,'month');
 document.querySelector('[data-action="food-progress-nav"][data-delta="-1"]').click();await tick();assert.ok(document.querySelector('[data-action="food-progress-current"]'),'past period exposes Current shortcut');assert.equal(document.querySelector('[data-action="food-progress-nav"][data-delta="1"]').disabled,false);
 document.querySelector('[data-action="food-progress-nav"][data-delta="1"]').click();await tick();assert.ok(!document.querySelector('[data-action="food-progress-current"]'),'forward scrub returns to current period');
 for(const [date,value] of [['2026-09-22','177.8'],['2026-09-23','177.6'],['2026-09-24','177.4'],['2026-09-25','177.2']]){await click('weight');await submit('weight',{value,date});}
 assert.ok(document.querySelector('[data-action="weight-all"]'),'individual weigh-ins exposes See all after five');
 await click('weight-all');assert.ok(document.querySelectorAll('.weight-all-list .list-row').length>=6,'all weigh-ins modal shows complete list');await click('close');
 const expectedCurrent=startOfWeek(localDate(),5);
 for(const row of document.querySelectorAll('[data-week]'))assert.equal(row.textContent.includes('Current week'),row.dataset.week===expectedCurrent);
 await click('settings');
 await submit('settings',{calories:'1600',protein:'130',heightInches:'68',unit:'lb'});
 assert.equal(JSON.parse(state.records.get('bob').payload).settings.weekStart,5,'saving goals preserves fixed Friday week start');
 await click('sign-out');await click('sign-in');await click('settings');
 assert.equal(document.querySelector('[name="weekStart"]'),null,'week start is no longer user-selectable');
 assert.ok(document.querySelector('main').textContent.includes('Weeks start Friday.'),'Friday boundary survives cloud reload');
 // Pass 4: preview staging, pagination, invalid files, cancellation and failed writes.
 const previewFile=async(kind,raw)=>{
  await click('import-data');await click(kind==='csv'?'import-csv':'restore');const f=document.querySelector('[data-form="import"]');
  Object.defineProperty(f.querySelector('[name="file"]'),'files',{value:[{name:'test.'+kind,size:raw.length,text:async()=>raw}]});
  f.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await tick();
 };
 const unchanged=JSON.parse(state.records.get('bob').payload);
 const incoming={...structuredClone(unchanged),foodEntries:unchanged.foodEntries.slice(0,1)};incoming.settings.dayResetMinutes=390;
 await previewFile('json',JSON.stringify(incoming));
 assert.ok(document.querySelector('.import-scroll'));assert.ok(document.querySelectorAll('.import-group').length>=1);
 assert.ok(document.querySelector('.import-summary').textContent.includes('replaces all'));
 assert.deepEqual(JSON.parse(state.records.get('bob').payload),unchanged);
 await click('close');assert.ok(!document.querySelector('.modal'));
 assert.deepEqual(JSON.parse(state.records.get('bob').payload),unchanged);
 const largeCSV='date,name,calories,protein,quantity\n'+Array.from({length:121},(_,i)=>`2026-09-27,Preview ${i},100,10,1`).join('\n');
 await previewFile('csv',largeCSV);
 assert.equal(document.querySelectorAll('#import-foodEntries>.import-record').length,50);
 const more=document.querySelector('[data-group="foodEntries"]');more.click();await tick();
 assert.equal(document.querySelectorAll('#import-foodEntries>.import-record').length,100);
 document.querySelector('[data-group="foodEntries"]').click();await tick();
 assert.equal(document.querySelectorAll('#import-foodEntries>.import-record').length,121);
 await click('close');assert.deepEqual(JSON.parse(state.records.get('bob').payload),unchanged);
 await previewFile('csv','date,name,calories,protein\n2026-09-27,Valid,100,10\n2026-09-27,Invalid,-1,10');
 assert.ok(document.querySelector('[role="alert"]'));assert.ok(!document.querySelector('[data-action="commit-import"]'));await click('close');
 await previewFile('json','{');assert.ok(!document.querySelector('[data-action="commit-import"]'));await click('close');
 const oneCSV='date,name,calories,protein\n2026-09-27,Import test,100,10';
 await previewFile('csv',oneCSV);state.fail=true;await click('commit-import');
 assert.deepEqual(JSON.parse(state.records.get('bob').payload),unchanged,'failed import leaves cloud data unchanged');
 assert.ok(document.querySelector('.import-alert').textContent.includes('not saved'));await click('close');await click('food');
 assert.ok(!document.querySelector('.food-preview').textContent.includes('Import test'),'failed import leaves in-memory data unchanged');
 state.fail=false;await click('settings');await previewFile('csv',oneCSV);await click('commit-import');
 assert.equal(JSON.parse(state.records.get('bob').payload).foodEntries.length,unchanged.foodEntries.length+1);
 await click('settings');await click('import-data');await click('paste-csv');let pasteForm=document.querySelector('[data-form="import"]');pasteForm.elements.text.value='recordType,date,bodyFatPercent\nweight,2026-09-30,21.9';pasteForm.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.ok(document.querySelector('.import-scroll'));await click('commit-import');assert.equal(JSON.parse(state.records.get('bob').payload).bodyFat.find(b=>b.date==='2026-09-30').value,21.9);
 await previewFile('csv',oneCSV);assert.ok(document.querySelector('.import-summary').textContent.includes('1 possible duplicates'));await click('close');
 // A read resolving after Cancel must not revive the preview.
 await click('import-data');await click('import-csv');const slowForm=document.querySelector('[data-form="import"]');let finishRead;
 Object.defineProperty(slowForm.querySelector('[name="file"]'),'files',{value:[{size:100,text:()=>new Promise(resolve=>{finishRead=resolve;})}]});
 slowForm.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await click('close');finishRead(oneCSV);await tick();
 assert.ok(!document.querySelector('.modal'));assert.ok(!document.querySelector('[data-action="commit-import"]'));
 // Device storage failures also keep the original records intact.
 await click('sign-out');
 assert.equal(localStorage.getItem('everyday-cloud-confirmed-v1:bob'),null,'explicit sign-out clears the account-specific confirmed copy');
 assert.equal(localStorage.getItem('everyday-cloud-recovery-v1:bob'),null,'explicit sign-out clears the account-specific recovery copy');
 await click('settings');
 const localBefore=localStorage.getItem('everyday-fitness-v1');
 await previewFile('csv',oneCSV);
 const originalSetItem=dom.window.Storage.prototype.setItem;
 dom.window.Storage.prototype.setItem=function(){throw Error('Storage full');};
 await click('commit-import');dom.window.Storage.prototype.setItem=originalSetItem;
 assert.equal(localStorage.getItem('everyday-fitness-v1'),localBefore);
 assert.ok(document.querySelector('.import-alert').textContent.includes('Storage full'));
 await click('close');await click('food');assert.ok(!document.querySelector('.food-preview').textContent.includes('Import test'));
 console.log('UI smoke passed: import review, pagination, validation, cancellation, delayed reads, atomic cloud/device failures and confirmation; Food empty/1–3/many entries, full log, historic add/edit/delete, today action; home hierarchy, dialog focus, dates, food, lifting, scrubbable nutrition periods, weigh-in see-all, progress, universal CSV/file+paste and JSON import/export, saved-food undo, body fat, cruise notes, account transitions, migration and save recovery.');
}finally{dom.window.close();await rm(temp,{recursive:true,force:true});}
